### ISSUE TITLE
help with rankings

### ISSUE THREAD

**Issue by SuperTisha** [2048khz-gachi-rmx/ImprovedAdminPhysgun#1]
hello, such a problem, I installed the mod "I have ulx" and I don't understand how to make it so that the ranks can have all the functions of the addon, let's say I can't unfreeze the player for a certain admin panel, and so on. If it's not difficult then help :)

**Comment by 2048khz-gachi-rmx** [comment]
If the ULX rank has permissions to pick up players, then damage protection and such will work automatically*.

For player freezing & unfreezing, the rank will need both `ulx freeze` and `ulx unfreeze` permissions.

![gmod_ZtMTfrC5LP](https://user-images.githubusercontent.com/44749188/211143765-a8be34ae-290a-46e1-ae3b-93effd31c833.png)

_\* i pushed a fix just now where only admin ranks were able to benefit from these; you should update your addon_

**Comment by SuperTisha** [comment]
Wow, it worked, thanks a lot! By the way, the addon is similar to the paid addon Billy's Admin Physgun
Enhancer, you can say the free version
